### ISSUE TITLE
Undesired behaviour in HotElectronDistribution.py

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#1]
If hottailgrid is disabled in the interface (via SetEnabled(False)), HotElectronDistribution still requires initialization or it will throw an exception (at line 160).

**Comment by Embreus** [comment]
Maybe we should make it such that if no density is provided to SetInitialProfiles, it automatically sets it to n_free? and if no temperature is provided, it sets it to the initial value of T_cold? 

It would be desirable to implement it in such a way that n and T do not necessarily have to be initialised before f_hot.

**Comment by hoppe93** [comment]
Sounds like a good idea. The second part of your comment is the difficult part, and I cannot possibly think of a way which could set the f_hot profile without knowing n and T? Two alternative solutions are:

1. Allow the f_hot profile to not be set in the Python interface. If not set there, the kernel should automatically initialize n and T when loading f_hot. (probably best)
2. Set n0 and T0 when ``verifySettings()`` is called on the HotTailDistributionFunction. This method is called right before saving the settings (although it can be called manually earlier, or bypassed by giving ``verify=False`` when saving)

**Comment by Embreus** [comment]
I _think_ that 2 could be a satisfactory option? Although abuses the vision of verifySettings I guess. Could it be set in todict() otherwise?

**Comment by hoppe93** [comment]
It feels like implementing it in ``todict()`` might be slightly even more abuse of the purpose of the method? Since it might then bypass the checks in ``verifySettings()``.

But I would probably favour 1. I haven't checked properly yet if it's reasonable, but it feels like an attractive solution as all settings are necessarily known when loaded by the kernel, and since we should be able to omit certain settings (i.e. n0 and T0) from the settings file.
