### ISSUE TITLE
Kinetic prescribed transport does not interpolate to the radial flux grid

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#102]
In `SimulationGenerator::ConstructTransportTerm_internal` when the prescribed transport is loaded using `LoadDataTR2P`, a flag should be passed indicating that it should be interpolated to the radial flux grid (like is done with LoadDataRT below, which Ida just fixed in 4d9ae37 -- this bug actually caused her simulations to crash because the transport coefficient on the edge was extrapolated to negative values)

**Comment by hoppe93** [comment]
No, that is not how it's supposed to work. The case of 2D (time-radius) coefficients is a bit special because it seems ``LoadDataRT()`` is indeed interpolating already the input data when loaded, in which case it probably makes more sense to assume that the user wants to include the magnetic axis and plasma edge on the input radial grid (although a better solution would probably be to separate ``LoadDataRT()`` into two parts, with interpolation being optional). For the 4D coefficients, however, the interpolation only happens when the coefficient needs to be evaluated (i.e. in ``TransportPrescribed.tcc``). I think this is as expected and is not a bug. Are you really sure that the simulations crash because of this?

**Comment by Embreus** [comment]
The situation may be different with 4D data, as the crash only occurred with 2D data using LoadDataRT. In radial transport terms we are supposed to evaluate the coefficients on the radial flux grid, but DREAM (in loaddata) interpolated the data to the regular r grid. Then, in a later stage, when we evaluated the coefficients on the boundary of the radial flux grid, it seemed to _extrapolate_ values from the  boundary of the r grid to which it had previously interpolated, despite the original settings data including the r_f boundary.
