### ISSUE TITLE
Possibly redundant code

### ISSUE THREAD

**Issue by Pinfar** [chalmersplasmatheory/DREAM#218]
Hey, 
I am quite new here and was browsing code base. Can you tell me why Solver::BuildJacobian has the same for loop executed twice?
Thanks,
Marcin

**Comment by hoppe93** [comment]
Hi! The two for loops in ``Solver::BuildJacobian()`` are not identical. In the first loop, the central call is to ``Operator::SetJacobianBlock()``, whereas in the second loop the call is made to ``Operator::SetJacobianBlockBC()``. The former just *adds* element to the jacobian matrix, whereas the latter *overwrites* already existing elements. Since switching from *adding* elements to *overwriting* elements in the PETSc matrix requires a (relatively expensive) ``MatAssemble()`` in between, it is not possible to make the two calls immediately after each other.

Hence it is necessary to have both of these very similar-looking for-loops.

**Comment by Pinfar** [comment]
Thanks. My background is purely computer science, so #210 might be a good starting point for me.
