### ISSUE TITLE
Set charge state Z0 in AddIon(...) 

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#38]
We should retire PRESCRIBED_FULLY_IONIZED etc and instead allow the shortcut 

    eqsys.n_i.addIon(name='name', Z=Z, Z0=Z0, iontype=Ions.IONS_PRESCRIBED, n=n)

where Z is the atomic number as usual, but Z0 is now the charge state (= 0 for neutral or = Z for fully ionized).

**Comment by hoppe93** [comment]
Sure, but I am not convinced that we should retired ``IONS_PRESCRIBED_FULLY_IONIZED`` et al? The notation ``Z0=...`` suggests that we are specifying just one charge state (rather than setting all other to zero), while ``IONS_PRESCRIBED_FULLY_IONIZED`` is quite verbose.

(Implementing the ``Z0=...`` interface should be very simple, though, as the ``IonSpecies`` class already has the ``initialize_XXX_charge_state()`` method for initializing ions just this way; it's just not exposed to ``addIon()``)

**Comment by Embreus** [comment]
For sure, I agree that we should keep the current methods, also for backwards-compatibility.
