### ISSUE TITLE
Inconsistent use of AdvectionInterpolationCoefficient and BoundaryCondition to set boundary conditions

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#45]
Currently, some boundary conditions are imposed via the AdvectionInterpolationCoefficient (e.g. (most?) internal boundary conditions) whereas some are set by BoundaryCondition terms. 

We should streamline how boundary conditions are set, and come up with a clean way to ensure that all jacobian contributions are correctly set on the boundary.

**Comment by Embreus** [comment]
I wonder if a possible solution that ensures that all jacobians are "automatically" accounted for could be to set boundary conditions via (say) a BoundaryConditionHandler object that is owned and handled by the AdvectionDiffusionTerm. This could then be called inside AdvectionTerm.set and DiffusionTerm.set on the boundary terms, and depending on which settings have been set for the BoundaryConditionHandler via the EquationSystem, it would set boundary fluxes with the information already available to AdvectionTerm and DiffusionTerm.

**Comment by hoppe93** [comment]
Could an option to the ``BoundaryConditionHandler`` be to just add an extra argument to ``BoundaryCondition::AddToJacobianBlock()`` and ``BoundaryCondition::SetJacobianBlock()``, which are called from ``Operator::SetJacobianBlock()`` and ``Operator::SetJacobianBlockBC()`` after all equation terms have been inserted into a given Jacobian matrix block? The new argument would be a pointer to the parent ``Operator`` from which we could access all terms in the operator, and iterate over ``AdvectionTerm``s and ``DiffusionTerm``s in order to make them build derivatives of their coefficients.

This should work as long as a ``BoundaryCondition`` applied to a given matrix block doesn't depend on an ``EquationTerm`` that is applied to a different matrix block (i.e. is part of a different ``Operator`` object).
